set clipboard=unnamed
set fileencodings=iso-2022-jp,euc-jp,sjis,utf-8
set ignorecase
set inccommand=split
set iskeyword+=-
set mouse=a
set noswapfile
set nowrapscan
set smartcase
set splitbelow
set splitright
set undofile
